---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: Install Java-jdk
  apt:
    name: default-jdk
  become: true

- name: Download Kafka
  get_url:
    url: http://mirrors.standaloneinstaller.com/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz
    dest: "./kafka.tgz"
  become: true

- name: Extract kafka.tgz
  shell:  "tar -xzvf ./kafka.tgz"
  become: true

- name: Move Kafka
  shell: "mv ./kafka_2.11-2.4.1 /etc/kafka"
  become: true

- name : Remove kafka.tgz
  file:
    path: "./kafka.tgz"
    state: absent
  become: true

- name: copy kafka service file
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
    owner: root
    mode: '0640'
  become: true

- name: copy zookeeper service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    mode: '0640'
  become: true

- name: enable zookeeper service
  systemd:
    enabled: yes
    name: zookeeper 

- name: enable kafka service
  systemd:
    enabled: yes
    name: kafka

- name: start zookeeper service
  systemd:
    state: started
    name: zookeeper 

- name: start kafka service
  systemd:
    state: started
    name: kafka