---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: Install Java-jdk
  apt:
    name: default-jdk
  become: true

- name: Download Kafka
  get_url:
    url: http://mirrors.standaloneinstaller.com/apache/kafka/2.4.1/kafka_2.11-2.4.1.tgz
    dest: "./kafka.tgz"
  become: true

- name: Extract kafka.tgz
  shell:  "tar -xzvf ./kafka.tgz"
  become: true

- name: Rename Kafka
  shell: "mv ./kafka_2.11-2.4.1 etc/kafka"
  become: true

- name : Remove kafka.tgz
  file:
    path: "./kafka.tgz"
    state: absent
  become: true

- name: Create zookeeper log directory 
  file:
    path: "var/log/zookeeper"
    state: directory
    mode: '0755'


- name: Create kafka log directory
  file:
    path: "var/log/kafka"
    state: directory
    mode: '0755'
                                            
- name: copy kafka service file
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
    owner: root
    mode: '0640'
  become: true
                                               
- name: copy zookeeper service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    mode: '0640'
  become: true

- name: enable zookeeper service
  systemd:
    name: zookeeper
    enabled: yes

- name: enable kafka service
  systemd:
    name: kafka
    enabled: yes
