---
- hosts: default
  become: true
  user: root
  vars:
    pip_install_packages:
    - name: docker
  roles:
    - zookeeper-kafka-server
    - kafka-topic
    - geerlingguy.pip
    - geerlingguy.docker
    - docker
