---
- name: Wait for kafka broker
  wait_for:
    port: 9092
    delay: 10

- name: Create first topic 
  shell: "/etc/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 2 --topic comand"
  become: true
