---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest 
  
- name: Install docker 
  pip:
    name: docker
    executable: "/usr/bin/pip3"

- name: Pull TP Docker image
  docker_image:
          name: jimilibilibob/tp-jupynotebook-git:202003
   
- name: Start a container with a command
  docker_container:
    name: TP
    image: jimilibilibob/tp-jupynotebook-git:202003
    command: start-notebook.sh --NotebookApp.password='sha1:ea68afae75d4:d1316963242d8eda06be2380d7f0d2c205fde124'
    ports: 8888:8888
